spring.application.name=devops-fundamentals

spring.datasource.url=jdbc:postgresql://localhost:5432/devops_fundamentals
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
